plugins {
  // https://github.com/nemerosa/versioning
  id 'net.nemerosa.versioning' version '3.1.0'
}

ext {
  testingCommonGradle = "https://raw.githubusercontent.com/interlok-testing/testing_common/refs/heads/master/common.gradle?timestamp=${new Date().getTime()}"
//  testingCommonGradle = "../testing_common/common.gradle"
  interlokTestingVersion = "0.1"
}

allprojects {
  apply from: "${testingCommonGradle}"
  // specify the version of the configuration.
  version=versioning.info.full
}


dependencies {
  interlokRuntime ("com.adaptris:interlok-swift:$interlokVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-scripting:$interlokVersion") { changing=true }
  
  interlokJavadocs group: "com.adaptris", name: "interlok-swift", version: "$interlokVersion", classifier: "javadoc", changing: true, transitive: false
  interlokJavadocs group: "com.adaptris", name: "interlok-scripting", version: "$interlokVersion", classifier: "javadoc", changing: true, transitive: false
  
  interlokTestRuntime ("com.adaptris:interlok-service-tester:$interlokVersion") { changing=true }
}
